apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  #- localhost:
  #    enabled: true
  - ssh:
      address: 192.168.4.93
      user: root
      port: 30022
      keyPath: /home/qiangyt/.ssh/id_rsa
    role: single # a single-node cluster host, the configuration can only contain one host
    installFlags:
    - --debug
    environment:
      HTTP_PROXY: 192.168.6.31:10081
  k0s:
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      #kind: Cluster
      kind: ClusterConfig
      metadata:
        name: k0s
      spec:
        images:
          calico:
            cni:
              image: calico/cni
              version: v3.16.2
        # api:
        #   k0sApiPort: 9443
        #   port: 6443
        # installConfig:
        #   users:
        #     etcdUser: etcd
        #     kineUser: kube-apiserver
        #     konnectivityUser: konnectivity-server
        #     kubeAPIserverUser: kube-apiserver
        #     kubeSchedulerUser: kube-scheduler
        # konnectivity:
        #   adminPort: 8133
        #   agentPort: 8132
        # network:
        #   kubeProxy:
        #     disabled: false
        #     mode: iptables
        #   kuberouter:
        #     autoMTU: true
        #     mtu: 0
        #     peerRouterASNs: ""
        #     peerRouterIPs: ""
        #   podCIDR: 10.244.0.0/16
        #   provider: kuberouter
        #   serviceCIDR: 10.96.0.0/12
        # podSecurityPolicy:
        #   defaultPolicy: 00-k0s-privileged
        # storage:
        #   type: etcd
        # telemetry:
        #   enabled: true
