#
# fraud-detection-app - fraud detection app
# Copyright © 2024 Yiting Qiang (qiangyt@wxcount.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

aws:
  region: ${AWS_REGION} # AWS region for the application
  access-key-id: ${AWS_ACCESS_KEY_ID} # AWS access key ID
  access-key-secret: ${AWS_ACCESS_KEY_SECRET} # AWS access key secret

app:
  sqs:
    detect-queue-url: ${AWS_SQS_DETECT_QUEUE_URL} # URL for the SQS detect queue
    detect-dead-letter-queue-url: ${AWS_SQS_DETECT_DEAD_LETTER_QUEUE_URL} # URL for the SQS detect dead letter queue
    alert-queue-url: ${AWS_SQS_ALERT_QUEUE_URL} # URL for the SQS alert queue

management:
  endpoints:
    enabled-by-default: true # Enable all management endpoints by default
    web.exposure.include: "*" # Expose all management endpoints over web
  info:
    build.enabled: false # Disable build info endpoint
    env.enabled: false # Disable environment info endpoint
    git.enabled: false # Disable git info endpoint
    java.enabled: false # Disable Java info endpoint
    os.enabled: false # Disable OS info endpoint
    process.enabled: false # Disable process info endpoint

spring:
  application.name: fraud_detection # Name of the Spring application
  devtools.restart.trigger-file: reloadtrigger # File to trigger a restart in devtools
  main:
    allow-circular-references: true # Allow circular references in Spring beans
    lazy-initialization: false # Disable lazy initialization
    kotlin.support.enabled: false # Disable Kotlin support
  data:
    rest:
      base-path: /api/data # Base path for data REST endpoints

springdoc:
  api-docs:
    path: /v3/api-docs # Path for OpenAPI documentation
