#
# fraud-detection-app - fraud detection app
# Copyright © 2024 Yiting Qiang (qiangyt@wxcount.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

aws:
  region: ${AWS_REGION}
  access-key-id: ${AWS_ACCESS_KEY_ID}
  access-key-secret: ${AWS_ACCESS_KEY_SECRET}

app:
  sqs:
    detect-queue-url: ${AWS_SQS_DETECT_QUEUE_URL}
    alert-queue-url: ${AWS_SQS_ALERT_QUEUE_URL}

management:
  endpoints:
    enabled-by-default: true
    web.exposure.include: "*"
  endpoint:
    env.show-values: ALWAYS 
    configprops.show-values: ALWAYS
  info:
    build.enabled: true
    env.enabled: true
    git.enabled: true
    java.enabled: true
    os.enabled: true
    process.enabled: true

spring:
  application.name: fraud_detection
  devtools.restart.trigger-file: reloadtrigger
  main:
    allow-circular-references: true
    lazy-initialization: false
    keep-alive: true # ensures that the JVM is kept alive, even if all threads are virtual threads. 
  mvc.throw-exception-if-no-handler-found: true
  servlet.session.persistent: false
springdoc:
  pre-loading-enabled: true
  writer-with-order-by-keys: true
  writer-with-default-pretty-printer: true
  disable-i18n: true
  show-spring-cloud-functions: false
  enable-groovy: false
  enable-spring-security: false
  enable-kotlin: false
  enable-hateoas: false
  enable-data-rest: false
  api-docs.version: openapi_3_1
  
  