apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
    spec:
      containers:
      - name: fraud-detection
        image: fraud-detection-image
        ports:
        - containerPort: 8080
        env:
        - name: SQS_QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: sqs-secret
              key: queue-url
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-service
spec:
  selector:
    app: fraud-detection
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
