apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
    spec:
      containers:
      - name: fraud-detection
        image: public.ecr.aws/g8s9f1z6/fraud-detection-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws-region
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws-access-key-id
        - name: AWS_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws-access-key-secret
        - name: AWS_SQS_QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws-sqs-queue-url
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-service
spec:
  selector:
    app: fraud-detection
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
