apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
    spec:
      containers:
      - name: fraud-detection
        image: public.ecr.aws/g8s9f1z6/fraud-detection-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws-region
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws-access-key-id
        - name: AWS_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws-access-key-secret
        - name: AWS_SQS_DETECT_QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws-sqs-detect-queue-url
        - name: AWS_SQS_DETECT_DEAD_LETTER_QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws-sqs-detect-dead-letter-queue-url
        - name: AWS_SQS_ALERT_QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws-sqs-alert-queue-url

